// JenkinsFile
// Jenkins Deploy할때 프로젝트 최상위에 Jenkinsfile을 참고해 수행됨!
pipeline {
    agent any
    environment {
        pjname = 'Springboot-MVC'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Build stage'
            }
        }
        stage('Test') {
            steps {
                echo 'Test stage'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy stage'
            }
        }
    }
}