#export KOPS_STATE_STORE=s3://squarebird-kops
#export KOPS_CLUSTER_NAME="k8s.testkops.com"
#export KOPS_CLUSTER_ZONES="ap-northeast-2a"
#export KOPS_MASTER_SIZE="t2.medium"
#export KOPS_MASTER_COUNT=1
#export KOPS_NODE_SIZE="t2.small"
#export KOPS_NODE_COUNT=2
#export KOPS_TOPOLOGY="private"
#export KOPS_DNS_ZONE="testkops.com"
#export KOPS_VPC_ID="vpc-086900a0555370392"

export KOPS_STATE_STORE=s3://<bucket name>
export KOPS_CLUSTER_NAME=<cluster name>
export KOPS_CLUSTER_ZONES=<cluster zone>
export KOPS_MASTER_SIZE=<master node instance size>
export KOPS_MASTER_COUNT=<master node instance count:int># only odd number
export KOPS_NODE_SIZE=<worker node instance size>
export KOPS_NODE_COUNT=<worker node instance count:int>
export KOPS_TOPOLOGY=<public or private>
export KOPS_DNS_ZONE=<dns zone name>
export KOPS_VPC_ID=<vpc id> # not required